# Generated by Django 5.0.6 on 2024-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(help_text='Enter the content of the note.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Enter the title of the note.', max_length=100),
        ),
    ]
